# SealedSecret Operator (Helm)
# https://github.com/disposab1e/sealed-secrets-operator-helm
#
# Version: v0.0.2, channel: alpha 
---
apiVersion: v1
kind: Namespace
metadata:
  name: cicd
  labels:
    openshift.io/cluster-monitoring: "true"
---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: sealed-secrets-operator-helm
  namespace: cicd
spec:
  targetNamespaces:
  - cicd
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  generation: 1  
  name: sealed-secrets-operator-helm
  namespace: cicd
spec:
  channel: alpha
  installPlanApproval: Automatic
  name: sealed-secrets-operator-helm
  source: community-operators
  sourceNamespace: openshift-marketplace
  startingCSV: sealed-secrets-operator-helm.v0.0.2
---