= OpenShift Recipes
:author: Hafid Haddouti
:toc: macro
:toclevels: 4
:sectlinks:
:sectanchors:

Collection of OpenShift recipes to manage common/infrastructure workload

toc::[]

== Overview

Using GitOps to manage a Kubernetes/OpenShift cluster with the cross-cutting capabilities like Pipeline, Secret Management or similar.
For the realization of the GitOps principles basically ArgoCD is used. In the current state the link:https://docs.openshift.com/container-platform/4.7/cicd/gitops/gitops-release-notes.html[OpenShift GitOps] option is used, which integrates ArgoCD and Pipeline.

The idea of the solution to manage a Kubernetes/OpenShift cluster in the GitOps way has the following pillars

* link:01-init[Init]: which installs the minium tools to support GitOps, here ArgoCD using the `Red Hat OpenShift GitOps`
* link:02-cluster-config[Cluster Config]: The ArgoCD project and app which will manage the cluster and maintain the capabilities. Here is the list of wanted capabilities defined - the descriptive state of your cluster.
* link:03-cluster-capabilities[Cluster Capabilities]: All the possible (cross-cutting) capabilities

== Installation

Configure the 'values.yaml' in link:02-cluster-config[Cluster Config] to select the desired state. Some capability examples are in link:03-cluster-capabilities[Cluster Capabilities], any other repository is how ever possible.

Follow the instruction in link:01-init[Init] to install.


== Overview

This collections holds various recipes to manage (infrastructure) workload like different Operators for Pipeline, ArgoCD, SealedSecrets etc. All recipes use the same structure

* *00_pre*: directory contains resources for the preparation phase
* *01_work*: directory for the main resources
* *02_post*: directory for post phase resource

It is not mandatory to use all directories.
Every recipe should also provide an `install.sh` and `remove.sh`, but can refer to the basic link:install.sh[] / link:remove.sh[].

Currently general yaml resource and kustomize yaml files are supported.

== Summary

Recipes collection to avoid further manual steps and get always the same outcome.

== References

N/A

== Open

N/A


== License

This article is licensed under the Apache License, Version 2.
Separate third-party code objects invoked within this code pattern are licensed by their respective providers pursuant
to their own separate licenses. Contributions are subject to the
link:https://developercertificate.org/[Developer Certificate of Origin, Version 1.1] and the
link:https://www.apache.org/licenses/LICENSE-2.0.txt[Apache License, Version 2].

See also link:https://www.apache.org/foundation/license-faq.html#WhatDoesItMEAN[Apache License FAQ]
.
