---
# Implement your Workload removal tasks here

- name: Set up ocp_recipe_opendatahub combined dictionary
  set_fact:
    ocp_recipe_opendatahub: >-
      {{ ocp_recipe_opendatahub_defaults
       | combine(ocp_recipe_opendatahub_vars    | default( {} ),
                 ocp_recipe_opendatahub_secrets | default( {}), recursive=true )
      }}

- name: Find all Open Data Hub instances
  k8s_facts:
    api_version: kfdef.apps.kubeflow.org/v1
    kind: KfDef
  register: r_kfdef

- name: Remove all Open Data Hub instances
  when: r_kfdef.resources | length > 0
  k8s:
    state: absent
    definition: "{{ item }}"
  loop: "{{ r_kfdef.resources }}"


- name: Get all InstallPlans
  k8s_facts:
    api_version: operators.coreos.com/v1alpha1
    kind: InstallPlan
    namespace: "{{ ocp_recipe_opendatahub.target_namespace }}"
  register: r_install_plans

- name: Find Open Data Hub InstallPlan Name
  set_fact:
    ocp_recipe_opendatahub_install_plan_name: "{{ r_install_plans.resources | to_json | from_json | json_query(query) }}"
  vars:
    query: >-
      [?starts_with(spec.clusterServiceVersionNames[0], 'opendatahub')].metadata.name|[0]

- name: Find all Open Data Hub related CSVs
  set_fact:
    ocp_recipe_opendatahub_csvs:  "{{ r_install_plans.resources | to_json | from_json | json_query(query) }}"
  vars:
    query: >-
      [?starts_with(spec.clusterServiceVersionNames[0], 'opendatahub')].spec.clusterServiceVersionNames

- name: Remove all Open Data Hub related CSVs
  when: ocp_recipe_opendatahub_csvs | length > 0
  k8s:
    state: absent
    api_version: operators.coreos.com/v1alpha1
    kind: ClusterServiceVersion
    name: "{{ item }}"
    namespace: "{{ ocp_recipe_opendatahub.target_namespace }}"
  loop: "{{ ocp_recipe_opendatahub_csvs[0] }}"

- name: Remove Subscription
  k8s:
    state: absent
    definition: "{{ lookup('template', item ) | from_yaml }}"
  loop:
  - ./templates/subscription.j2

- name: Remove all config and instance
  k8s:
    state: absent
    definition: "{{ lookup('file', item ) | from_yaml }}"
  loop:
  - ./files/namespace.yaml


- name: Remove InstallPlan
  when:
  - ocp_recipe_opendatahub_install_plan_name is defined
  - ocp_recipe_opendatahub_install_plan_name |d("") | length > 0
  k8s:
    state: absent
    api_version: operators.coreos.com/v1alpha1
    kind: InstallPlan
    name: "{{ ocp_recipe_opendatahub_install_plan_name }}"
    namespace: "{{ ocp_recipe_opendatahub.target_namespace }}"


# Leave this as the last task in the playbook.
- name: remove_workload tasks complete
  debug:
    msg: "Remove Workload tasks completed successfully."
  when: not silent|bool
