---

- name: Running prepare tasks
  include_tasks:
    file: ./prepare.yml
  when: 
  - ACTION is defined

- name: Prepare ansible roles
  include_tasks:
    file: ./prepare_ansible.yml
  when: 
  - ACTION is defined
  
- name: Running task for EFS provisioning
  block:  
  - name: Running AWS tasks
    include_tasks:
      file: ./aws.yml
    when: 
    - ACTION is defined
  
  - name: Debug Filesystem ID
    debug:
      msg: "{{ cf_stack.stack_outputs.FileSystemId }}"

  - name: Running Helm to install EFS in OCP tasks
    include_tasks:
      file: ./ocp_efs.yml
    when: 
    - ACTION is defined

  
- name: Running cleanup tasks
  include_tasks:
    file: ./cleanup.yml



    
    
