# Generic definition to create various ArgoCD Applications using the config
{{- if .Values.argocd.create -}}
{{- range .Values.argocd.apps }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .name | quote }}
  namespace: {{ .namespace | quote }}
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: {{ .namespace | quote }}
    server: {{ .server | default "https://kubernetes.default.svc" }}
  project: {{ .project | quote }}
  source:
    path: {{ .path | quote }}
    repoURL: {{ .repo | quote }}
    targetRevision: {{ .revision | quote }}
  syncPolicy:
    automated:
      prune: {{ .prune | default true }}
      selfHeal: {{ .selfHeal | default true }}
---
{{- end }}
{{- end }}
