# Namespace
---
apiVersion: v1
kind: Namespace
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "-10"
  labels:
    kubernetes.io/metadata.name: argocd-demo
    argocd.argoproj.io/managed-by: openshift-gitops
  name: argocd-demo