# Kustomize

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization


# since Kustomize 4.3.0
# in case fetching chart not from (remote) repo a local directory named "charts" is expected, holding the helm charts
helmCharts:
- name: helm-demo
  #repo: https://github.com/stocktrader-ops/helm-chart-sonarqube//charts/sonarqube?ref=sonarqube-9.6.3
  version: 9.6.3
  releaseName: helm-demo
  namespace: argocd-demo
  valuesInline:
    dummy: new-value


resources:
- 000-ns.yaml
- 04-tasks/task-deploy-from-source.yaml
- 04-tasks/task-maven.yaml
- 04-tasks/task-kaniko.yaml
- 04-tasks/task-buildah-privileged.yaml