# SealedSecret Operator (Helm)
# https://github.com/disposab1e/sealed-secrets-operator-helm
#
# Version: v0.0.2, channel: alpha 
---
apiVersion: v1
kind: Namespace
metadata:
  name: openshift-serverless
  labels:
    openshift.io/cluster-monitoring: "true"
---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: openshift-serverless
  namespace: openshift-serverless
spec: {}
#  targetNamespaces:
#  - openshift-serverless
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata: 
  name: serverless-operator
  namespace: openshift-serverless
spec:  
  channel: stable
  installPlanApproval: Automatic
  name: serverless-operator
  source: redhat-operators
  sourceNamespace: openshift-marketplace
  startingCSV: serverless-operator.v1.14.1