---
apiVersion: v1
kind: ConfigMap
metadata:
  name: app1-scripts
data:
  secrets-output.sh: |
    echo "secrets-output.sh script"
    while [ true ]; do
      
      echo "$(date '+%Y-%m-%d %H:%M:%S'): [From Main container] ...waiting..." >> /logs/test.log; 

      echo "[Main container] ...waiting..."

      sleep 15
    done;  
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app1-deployment
  labels:
    app: app1
    {{- include "helm-demo.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app1
  template:
    metadata:
      labels:
        app: app1    
        {{- include "helm-demo.labels" . | nindent 8 }}   
    spec:
      # Specific sa, relevant for Vault interaction
      serviceAccountName: sa-app1
      containers:
      - name: app1
        image: busybox:1.28
        command: ['sh', '-c', '/scripts/secrets-output.sh']
        volumeMounts:
          # Mount for the logs, shared with sidecar
          - name: logs
            mountPath: /logs
          # Mount from ConfigMap holding a script
          - name: app1-scripts-configmap
            mountPath: /scripts
      volumes:
        - name: logs
          emptyDir: {}
        - name: app1-scripts-configmap
          configMap:
            name: app1-scripts
            defaultMode: 0777