---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: "argocd-demo-edit-rb"
roleRef:
  apiGroup: rbac.authorization.k8s.io  
  kind: ClusterRole
  name: "edit"
subjects:
- kind: ServiceAccount
  name: "argocd-argocd-application-controller"
  namespace: argocd-demo
  #namespace: openshift-gitops
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: "openshift-gitopsargocd-demo-edit-rb"
  namespace: argocd-demo
roleRef:
  apiGroup: rbac.authorization.k8s.io  
  kind: ClusterRole
  name: "edit"
subjects:
- kind: ServiceAccount
  name: "openshift-gitops-argocd-application-controller"
  #namespace: argocd-demo
  namespace: openshift-gitops