---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: "argocd-demo-edit-rb"
roleRef:
  apiGroup: rbac.authorization.k8s.io  
  kind: ClusterRole
  name: "edit"
subjects:
- kind: ServiceAccount
  name: "argocd-argocd-application-controller"
  namespace: argocd-demo