apiVersion: v1
kind: ServiceAccount
metadata:
  name: "sa-app1"
  labels:
    {{- include "helm-demo.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
