# Operator instances
# 
---
apiVersion: v1
kind: Namespace
metadata:
  name: istio-system
  labels:
    openshift.io/cluster-monitoring: "true"
  annotations:
    argocd.argoproj.io/hook: PreSync
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: servicemesh-role
  namespace: istio-system
  annotations:
    argocd.argoproj.io/hook: PreSync
rules:
# Permissions to create resources in associated Tasks
- apiGroups: ["maistra.io"]
  resources: ["servicemeshcontrolplanes"]
  verbs: ["create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: servicemesh-role-binding
  namespace: istio-system
  annotations:
    argocd.argoproj.io/hook: PreSync
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: servicemesh-role
subjects:
- kind: ServiceAccount
  name: openshift-gitops-argocd-application-controller
  namespace: openshift-gitops
---
apiVersion: maistra.io/v2
kind: ServiceMeshControlPlane
metadata:
  name: basic
  namespace: istio-system
  annotations:
    argocd.argoproj.io/hook: PostSync
spec:
  version: v2.0
  tracing:
    type: Jaeger
    sampling: 10000
  addons:
    jaeger:
      name: jaeger
      install:
        storage:
          type: Memory
    kiali:
      enabled: true
      name: kiali
    grafana:
      enabled: true
---
