# Red Hat Service Binding Operator
# https://github.com/redhat-developer/service-binding-operator
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: rh-service-binding-operator
  namespace: openshift-operators 
spec:
  channel: stable
  installPlanApproval: Automatic
  name: rh-service-binding-operator
  source: redhat-operators
  sourceNamespace: openshift-marketplace