= OpenShift Recipes: Red Hat Service Binding Operator
:author: Hafid Haddouti
:toc: macro
:toclevels: 4
:sectlinks:
:sectanchors:

Red Hat Service Binding Operator, with Kustomize

toc::[]

== Overview

Deploys link:https://github.com/redhat-developer/service-binding-operator[Red Hat Service Binding Operator], a possibility to manage services from IBM Cloud catalogue. 

|===
| Title | Red Hat Service Binding Operator
| Status | In testing 
| Deploy Model | kustomize
| Dependencies | n/a
| OCP Version | >= 4.6
|===

== Preparation

N/A

== Post-Action

N/A

== Summary

Red Hat Service Binding Operator installed.

== References

N/A

== Open

N/A


== License

This article is licensed under the Apache License, Version 2.
Separate third-party code objects invoked within this code pattern are licensed by their respective providers pursuant
to their own separate licenses. Contributions are subject to the
link:https://developercertificate.org/[Developer Certificate of Origin, Version 1.1] and the
link:https://www.apache.org/licenses/LICENSE-2.0.txt[Apache License, Version 2].

See also link:https://www.apache.org/foundation/license-faq.html#WhatDoesItMEAN[Apache License FAQ]
.
