# ExternalSecret: Credentials for the PostgreSQL DB
# excepts: 
# - external-secrets-operator is in the cluster
# - ...and configured/connected to SM
---
apiVersion: external-secrets.io/v1alpha1
kind: ExternalSecret
metadata:
  name: external-secret-one
  namespace: sonarqube
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: secretstore-ibm-secretsmanager
    kind: ClusterSecretStore
  target:
    name: sonarqube-db-secret
    creationPolicy: Owner
  data:
  - secretKey: pw
    remoteRef:
      key: 'username_password/75a30ee2-fdbe-d3bc-2daa-f793836becd8'
      property: 'password'
