---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: argocd-edit
  namespace: openshift-cloud-credential-operator
subjects:
- kind: ServiceAccount
  name: pipeline
  namespace: gitops-config
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: edit 