---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: argocd-edit
  namespace: openshift-cloud-credential-operator
subjects:
- kind: ServiceAccount
  name: openshift-gitops-argocd-application-controller
  namespace: openshift-gitops
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: edit 
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: cloudcredential-role
  namespace: openshift-cloud-credential-operator
rules:
- apiGroups: ["cloudcredential.openshift.io"]
  resources: ["credentialsrequests"]
  verbs: ["create", "update", "patch", "delete"]
---
# RoleBinding to get the credentials
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: argocd-cr-edit
  namespace: openshift-cloud-credential-operator
subjects:
- kind: ServiceAccount
  name: openshift-gitops-argocd-application-controller
  namespace: openshift-gitops
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: cloudcredential-role
---
# RoleBinding in default namespace where the efs-provisioner will be installed
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: aws-efs-role
  namespace: default
rules:
- apiGroups: ["policy"]
  resources: ["podsecuritypolicies"]
  verbs: ["create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: argocd-aws-efs
  namespace: gitops-config
subjects:
- kind: ServiceAccount
  name: openshift-gitops-argocd-application-controller
  namespace: openshift-gitops
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: aws-efs-role
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: argocd-aws-efs
  namespace: openshift-gitops
subjects:
- kind: ServiceAccount
  name: openshift-gitops-argocd-application-controller
  namespace: openshift-gitops
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: aws-efs-role
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: argocd-cr-admin
  namespace: gitops-config
subjects:
- kind: ServiceAccount
  name: openshift-gitops-argocd-application-controller
  namespace: openshift-gitops
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: admin