= OpenShift Recipes: Red Hat API Designer
:author: Hafid Haddouti
:toc: macro
:toclevels: 4
:sectlinks:
:sectanchors:

link:#[Red Hat API Designer], API / OpenAPI editor.

toc::[]

== Overview

Installs Red Hat API Designer. API Designer is a lightweight version of link:../apicurio-studio[Apicurio Studio] without storage capabilities.

|===
| Title | Red Hat API Designer
| Status | In testing 
| Deploy Model | kustomize
| Dependencies | n/a
| OCP Version | >= 4.6
|===

== Usage

n/a

== Summary

Red Hat API Designer is installed.

== References

* n/a

== Open

N/A


== License

This article is licensed under the Apache License, Version 2.
Separate third-party code objects invoked within this code pattern are licensed by their respective providers pursuant
to their own separate licenses. Contributions are subject to the
link:https://developercertificate.org/[Developer Certificate of Origin, Version 1.1] and the
link:https://www.apache.org/licenses/LICENSE-2.0.txt[Apache License, Version 2].

See also link:https://www.apache.org/foundation/license-faq.html#WhatDoesItMEAN[Apache License FAQ]
.
