# GitLab Runner Operator installation
#
# gitlab-runner-operator
# Version: v13.10.0, channel: stable
#
# - Operator subscription
---
apiVersion: v1
kind: Namespace
metadata:
  name: gitlab-config
  labels:
    openshift.io/cluster-monitoring: "true"
---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: gitlab-config
  namespace: gitlab-config
spec:
  targetNamespaces:
  - gitlab-config
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  generation: 1  
  name: gitlab-runner-operator
  namespace: gitlab-config
spec:
  channel: stable
  installPlanApproval: Automatic
  name: gitlab-runner-operator
  source: community-operators
  sourceNamespace: openshift-marketplace
  startingCSV: gitlab-runner-operator.v13.10.0