# Tekton RBAC
# 
# - Allow ArgoCD to modify Tekton CRDs
# - Allow pipeline to exec
{{- range .Values.namespaces }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: tekton-role
  namespace: {{ . | quote }}
rules:
# EventListeners need to be able to fetch all namespaced resources
- apiGroups: ["triggers.tekton.dev"]
  resources: ["eventlisteners", "triggerbindings", "triggertemplates", "triggers"]
  verbs: ["get", "list", "watch"]
# Permissions to create resources in associated Tasks
- apiGroups: ["tekton.dev"]
  resources: ["tasks", "task", "taskruns", "pipelines", "pipelineresources"]
  verbs: ["create", "update", "patch", "delete"]
- apiGroups: [""]
# configmaps is needed for updating logging config
  resources: ["configmaps"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
# serviceaccounts, to create later a service account
  resources: ["serviceaccounts"]
  verbs: ["create", "update", "patch", "delete", "get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: tekton-role-binding
  namespace: {{ . | quote }}
subjects:
- kind: ServiceAccount
  name: argocd-cluster-argocd-application-controller
  namespace: openshift-gitops
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: tekton-role
{{- end }}

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: pipeline
  namespace: openshift-gitops
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: edit
  namespace: openshift-gitops
subjects:
- kind: ServiceAccount
  name: pipeline
  namespace: openshift-gitops
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: edit