# OpenShift Elasticsearch Operator
# 
# elasticsearch-operator
# Version: 4.6.x, channel: 4.6
#
---
apiVersion: v1
kind: Namespace
metadata:
  name: openshift-operators-redhat
  labels:
    openshift.io/cluster-monitoring: "true"
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  generation: 1  
  name: elasticsearch-operator
  namespace: openshift-operators-redhat 
  labels:
    operators.coreos.com/elasticsearch-operator.openshift-operators-redhat: ""
spec:
  channel: "4.6"
  installPlanApproval: Automatic
  name: elasticsearch-operator
  source: redhat-operators
  sourceNamespace: openshift-marketplace
  startingCSV: elasticsearch-operator.4.6.0-202104161407.p0
---

