# Apicurito Operator installation
#
# apicurito
# Version: v1.0.0, channel: alpha
#
# - Operator subscription
---
apiVersion: v1
kind: Namespace
metadata:
  name: apicurito
  labels:
    openshift.io/cluster-monitoring: "true"
---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: apicurito
  namespace: apicurito
spec:
  targetNamespaces:
  - apicurito
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  generation: 1  
  name: apicurito
  namespace: apicurito 
spec:
  channel: alpha
  installPlanApproval: Automatic
  name: apicurito
  source: community-operators
  sourceNamespace: openshift-marketplace
  startingCSV: apicuritooperator.v0.1.0
---
apiVersion: apicur.io/v1alpha1
kind: Apicurito
metadata:
  name: apicurito-service
  namespace: apicurito
spec:
  size: 1
  image: 'apicurio/apicurito-ui:latest'

