# ArgoCD Operator installation
#
# openshift-gitops-operator
# Version: v1.0.0, channel: preview
#
# - Operator subscription
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  generation: 1  
  name: openshift-gitops-operator
  namespace: openshift-operators
  labels:
    operators.coreos.com/openshift-gitops-operator.openshift-operators: ""
spec:
  channel: preview
  installPlanApproval: Automatic
  name: openshift-gitops-operator
  source: redhat-operators
  sourceNamespace: openshift-marketplace
  startingCSV: openshift-gitops-operator.v1.0.0