# Kustomize: Common Tekton tasks and pipeline

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

#namespace: openshift-gitops
#commonLabels:
#  pipeline: tekton101
#  deploy: argocd


resources:
- 000-tekton-rbac.yaml
- 010-tekton-common-tasks.yaml