# ExternalSecret: Credentials for the PostgreSQL DB
# excepts: 
# - external-secrets-operator is in the cluster
# - ...and configured/connected to SM
---
apiVersion: external-secrets.io/v1alpha1
kind: ExternalSecret
metadata:
  name: external-secret-sonarqube-db
  namespace: sonarqube
spec:
  refreshInterval: 1m0s
  secretStoreRef:
    name: secretstore-ibm-secretsmanager
    kind: ClusterSecretStore
  target:
    name: sonarqube-db-secret
    creationPolicy: Owner
  data:
  - secretKey: pw
    remoteRef:
      key: 'username_password/0225e4a3-5f22-47e8-29ef-eb9aaa0230fd'
      property: 'password'
