# Helm values for: ArgoCD Cluster Config using app-of-apps pattern

argocd:
  # Specifies whether a ArgoCD app createion is wanted or not
  create: true

  apps:
    - name: sealedsecret
      repo: https://github.com/ocp-universe/ocp-recipes
      path: 03-cluster-capabilities/sealedsecret
      revision: main
      namespace: openshift-gitops
      # optional fields
      #server: 
      project: argocd-bootstrap-project
      #prune: true/false
      #selfHeal: true/false      
    - name: api-designer
      repo: https://github.com/ocp-universe/ocp-recipes
      path: 03-cluster-capabilities/api-designer
      revision: main
      namespace: openshift-gitops
      # optional
      #server: 
      project: argocd-bootstrap-project      
    - name: tekton-common-manifest
      repo: https://github.com/ocp-universe/ocp-recipes
      path: 03-cluster-capabilities/tekton-common-tasks/helm
      revision: main
      namespace: openshift-gitops
      # optional
      #server: 
      project: argocd-bootstrap-project
#    - name: service-mesh
#      repo: https://github.com/ocp-universe/ocp-recipes
#      path: 03-cluster-capabilities/servicemesh
#      revision: main
#      namespace: openshift-gitops
#      # optional
#      #server: 
#      project: argocd-bootstrap-project
#    - name: ocp-web-terminal
#      repo: https://github.com/ocp-universe/ocp-recipes
#      path: 03-cluster-capabilities/web-terminal
#      revision: main
#      namespace: openshift-gitops
#      # optional
#      #server: 
#      project: argocd-bootstrap-project
    - name: ocp-rhacm
      repo: https://github.com/ocp-universe/ocp-recipes
      path: 03-cluster-capabilities/rhacm
      revision: main
      namespace: openshift-gitops
      # optional
      #server: 
      project: argocd-bootstrap-project
