# Helm values for: ArgoCD Cluster Config using app-of-apps pattern

argocd:
  # Specifies whether a ArgoCD app creation is wanted or not
  create: true
  cluster:
    name: "cluster-name"
    env: "stage"
    
  apps:
    - name: tekton-common-manifest
      repo: https://github.com/ocp-universe/ocp-recipes
      path: 03-cluster-capabilities/tekton-common-tasks/helm
      revision: main
      namespace: openshift-gitops
      # optional
      #server: 
      project: argocd-bootstrap-project
      ignores:
      - group: tekton.dev
        kind: TaskRun
        jsonPointers:
        - /metadata/labels
        - /metadata/annotations
    - name: fuse
      repo: https://github.com/ocp-universe/ocp-recipes
      path: 03-cluster-capabilities/fuse/helm
      revision: main
      namespace: openshift-gitops
      # optional fields
      #server: 
      project: argocd-bootstrap-project
      #prune: true/false
      #selfHeal: true/false    
      ignores:
      - group: tekton.dev
        kind: TaskRun
        jsonPointers:
        - /metadata/labels
        - /metadata/annotations
    
