# Helm values for: ArgoCD Cluster Config using app-of-apps pattern

argocd:
  # Specifies whether a ArgoCD app createion is wanted or not
  create: true

  apps:
    - name: fuse
      repo: https://github.com/ocp-universe/ocp-recipes
      path: 03-cluster-capabilities/fuse
      revision: main
      namespace: openshift-gitops
      # optional fields
      #server: 
      project: argocd-bootstrap-project
      #prune: true/false
      #selfHeal: true/false      
    
