# Set permission to Tekton pipeline
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: edit
  namespace: gitops-config
subjects:
- kind: ServiceAccount
  name: pipeline
  namespace: gitops-config
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: edit 