# Web-Terminal
#
# Using Tekton and ansible-runner
---
apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  name: web-termina-task-run2
spec:
  taskRef:
    name: ansible-runner
  params:
    # ansible-runner parameters
    - name: project-dir
      value: '03-cluster-capabilities/web-terminal'
    - name: args
      value:
      - '-p main.yml'
      - '--project-dir 03-cluster-capabilities/web-terminal'
      #- '--project-dir "web-terminal"'
    - name: largs
      value: '-p main.yml --project-dir 03-cluster-capabilities/web-terminal'            
  workspaces:
    - name: runner-dir
      emptyDir: {}
  podTemplate:
    securityContext:
      runAsUser: 0
