# Web-Terminal
#
# Using Tekton and ansible-runner
---
apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  name: web-termina-task-run2
spec:
  taskRef:
    name: ansible-runner
  params:
    # ansible-runner parameters
    - name: project-dir
      value: '.'
    - name: args
      value:
      - '-p main.yml'
  workspaces:
    - name: runner-dir
      emptyDir: {}
  