# OpenShift Elasticsearch Operator
# 
# elasticsearch-operator
# Version: 4.6.x, channel: 4.6
#
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: elasticsearch-operator
spec:
  channel: "5.0"
  installPlanApproval: Automatic
  name: elasticsearch-operator
  source: redhat-operators
  sourceNamespace: openshift-marketplace
  startingCSV: elasticsearch-operator.5.0.3-6

