= OpenShift Recipes: Red Hat 
:author: Hafid Haddouti
:toc: macro
:toclevels: 4
:sectlinks:
:sectanchors:

OpenShift Application Data Protection Operator (OADP) for data, backup and recovery use cases.

toc::[]

== Overview

Deploys link:https://github.com/konveyor/oadp-operator[OADP] from Konveyor umbrella project into a Kubernetes/OpenShift cluster.
Covers the use case about data protection, backup and recovery and base on link:https://velero.io/[Velero].

|===
| Title | OpenShift Application Data Protection Operator
| Status | In testing 
| Deploy Model | kustomize
| Dependencies | n/a
| OCP Version | >= 4.6
|===

== Action

----
$ oc apply -k .
----

== Summary

OpenShift Application Data Protection Operator installed.

== References

* Konveyor: link:https://www.konveyor.io/[]
* Konveyor - OADP Operator: link:https://github.com/konveyor/oadp-operator[]

== Open

N/A


== License

This article is licensed under the Apache License, Version 2.
Separate third-party code objects invoked within this code pattern are licensed by their respective providers pursuant
to their own separate licenses. Contributions are subject to the
link:https://developercertificate.org/[Developer Certificate of Origin, Version 1.1] and the
link:https://www.apache.org/licenses/LICENSE-2.0.txt[Apache License, Version 2].

See also link:https://www.apache.org/foundation/license-faq.html#WhatDoesItMEAN[Apache License FAQ]
.
