= OpenShift Recipes: IBM Cloud Operator
:author: Hafid Haddouti
:toc: macro
:toclevels: 4
:sectlinks:
:sectanchors:

IBM Cloud Operator, with Kustomize

toc::[]

== Overview

Deploys link:https://github.com/IBM/cloud-operators[IBM Cloud Operator], a possibility to manage services from IBM Cloud catalogue. 

|===
| Title | IBM Cloud Operator
| Status | In testing 
| Deploy Model | kustomize
| Dependencies | n/a
| OCP Version | >= 4.6
|===

== Preparation

N/A

== Post-Action

Create an IBM API Key and store it for the operator, a detailed instruction is in the repo link:https://github.com/IBM/cloud-operators#using-a-service-id[available].
A summary consists of following steps

. Create Service ID and API Key

----
ibmcloud iam service-id-create serviceid-ico -d "Service ID for IBM Cloud Operator"
ibmcloud iam service-policy-create serviceid-ico --roles Administrator --resource-group-name default --region eu-de
ibmcloud iam service-api-key-create apikey-ico serviceid-ico -d "API Key for IBM Cloud Operator, using Service ID" --output json | jq -r ".apikey"
----

. Create own namespace holding the `ConfigMap` and `Secret` objects for the operator
. Create at the minimum the default `ConfigMap` and `Secret` in the new namespace

----
$ kubectl create ns devops-common

$ kubectl get cm,secret -n devops-common | grep ibmcloud

configmap/default-ibmcloud-operator-defaults   0      4m8s
secret/default-ibmcloud-operator-secret   Opaque                                2      4m8s
----

== Summary

IBM Cloud Operator installed.

== References

N/A

== Open

N/A


== License

This article is licensed under the Apache License, Version 2.
Separate third-party code objects invoked within this code pattern are licensed by their respective providers pursuant
to their own separate licenses. Contributions are subject to the
link:https://developercertificate.org/[Developer Certificate of Origin, Version 1.1] and the
link:https://www.apache.org/licenses/LICENSE-2.0.txt[Apache License, Version 2].

See also link:https://www.apache.org/foundation/license-faq.html#WhatDoesItMEAN[Apache License FAQ]
.
