# Resources to build and deploy new ArgoCD image with Vault plugin using
# Git repo and Dockerfile
---
kind: ImageStream
apiVersion: image.openshift.io/v1
metadata:
  name: argocd-rhel8
  namespace: openshift-gitops
  labels:
    app: argocd-vault
    app.kubernetes.io/component: argocd-vault
    app.kubernetes.io/instance: argocd-vault
spec:
  lookupPolicy:
    local: false
  tags:
    - name: latest
      annotations:
        openshift.io/imported-from: >-
          registry.redhat.io/openshift-gitops-1/argocd-rhel8@sha256:1da88dd045197f3a64c9508e290fd64f23dc0648bc304f6416e952d9404bee57
      from:
        kind: DockerImage
        name: >-
          registry.redhat.io/openshift-gitops-1/argocd-rhel8@sha256:1da88dd045197f3a64c9508e290fd64f23dc0648bc304f6416e952d9404bee57
      generation: 2
      importPolicy: {}
      referencePolicy:
        type: Source
---
kind: ImageStream
apiVersion: image.openshift.io/v1
metadata:
  name: argocd-vault
  namespace: openshift-gitops
  labels:
    app: argocd-vault
    app.kubernetes.io/component: argocd-vault
    app.kubernetes.io/instance: argocd-vault  
spec:
  lookupPolicy:
    local: false
---
kind: BuildConfig
apiVersion: build.openshift.io/v1
metadata:
  name: argocd-vault
  namespace: openshift-gitops
  labels:
    app: argocd-vault
    app.kubernetes.io/component: argocd-vault
    app.kubernetes.io/instance: argocd-vault
  annotations:
    openshift.io/generated-by: OpenShiftNewApp
spec:
  triggers:
    - type: ConfigChange
#    - type: ImageChange
#      imageChange:
#        lastTriggeredImageID: >-
#          registry.redhat.io/openshift-gitops-1/argocd-rhel8@sha256:aed92fa8409874ab61c6c4ac1ace9cced6eb58137d8ed5a4719abdf9de85ef5a
  runPolicy: Serial
  source:
    type: Git
    git:
      uri: 'https://github.com/ocp-universe/ocp-recipes'
    contextDir: 01-init/argocd-vault
  strategy:
    type: Docker
    dockerStrategy:
      from:
        kind: ImageStreamTag
        name: 'argocd-rhel8:latest'
  output:
    to:
      kind: ImageStreamTag
      name: 'argocd-vault:latest'
  resources: {}
  postCommit: {}
  nodeSelector: null
  successfulBuildsHistoryLimit: 5
  failedBuildsHistoryLimit: 5
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: argocd-vault
  namespace: openshift-gitops
  labels:
    app: argocd-vault
    app.kubernetes.io/component: argocd-vault
    app.kubernetes.io/instance: argocd-vault
spec:
  replicas: 1
  selector:
    matchLabels:
      deployment: argocd-vault
  template:
    metadata:
      creationTimestamp: null
      labels:
        deployment: argocd-vault
    spec:
      containers:
        - name: argocd-vault
          image: >-
            image-registry.openshift-image-registry.svc:5000/openshift-gitops/argocd-vault:latest
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: IfNotPresent
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
