# Kustomize: Operator

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

#namespace: openshift-gitops
#commonLabels:
#  pipeline: tekton101
#  deploy: argocd

configMapGenerator:
- behavior: merge
  name: argocd-cm
  literals:
  - |
    resource.customizations.health.operator.external-secrets.io_OperatorConfig: |
      hs = {}
      hs.status = "Healthy"
      return hs



resources:
- 000-operator.yaml
- 001-rbac.yaml
- 001-instance.yaml

