# ArgoCD Operator installation
#
# openshift-gitops-operator
# Version: v1.2.0, channel: preview
#
# - Operator subscription
---
apiVersion: v1
kind: Namespace
metadata:
  name: openshift-gitops
  labels:
    openshift.io/cluster-monitoring: "true"
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: openshift-gitops-operator
  namespace: openshift-operators
#  labels:
#    operators.coreos.com/openshift-gitops-operator.openshift-operators: ""
spec:
  channel: stable
  installPlanApproval: Automatic
  name: openshift-gitops-operator
  source: redhat-operators
  sourceNamespace: openshift-marketplace
  startingCSV: openshift-gitops-operator.v1.2.0