# OpenShift Elasticsearch Operator
# 
# elasticsearch-operator
# Version: 4.6.x, channel: 4.6
#
---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: servicemesh-umbrella
  namespace: openshift-gitops
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  generators:
  - git:
      repoURL: https://github.com/ocp-universe/ocp-recipes.git
      revision: main
      files:
      - path: "03-cluster-capabilities/servicemesh-umbrella/servicemesh-config.json"
  template:
    metadata:
      name: '{{name}}'
    spec:
      project: argocd-bootstrap-project
      source:
        repoURL: '{{repo}}'
        targetRevision: '{{revision}}'
        path: '{{path}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: openshift-gitops
      syncPolicy:
        automated:
          prune: true
          selfHeal: true