= OpenShift Recipes: Cluster Config
:author: Hafid Haddouti
:toc: macro
:toclevels: 4
:sectlinks:
:sectanchors:

Kubernetes/OpenShift GitOps - Manage the capabilities or your cluster. The cluster configuration.

toc::[]

== Overview

This section contains the Cluster Configuration part to configure ArgoCD with the desired cluster capabilities.
In a previous version was this solved with with `helm` and the link:helm/values.yaml[] contains the configuration for the desired capabilities.
But with the enhancement in ArgoCD with `ApplicationSet` is this optimized to the link:cluster-config.json[] representing the list of desired capabilities.

== Installation

Generally this is not installed manually. During the link:../01-init[initialization] will be a new ArgoCD App configured and linked to this repo.

To configure the desired cluster state with the needed capabilities, adjust the link:cluster-config.json[] considering the following structure

|===
| `name` | Name of the capability, will be used as identify in ArgoCD.
| `repo` | GitHub repository to the capability holding the logic to install it. All link:https://argoproj.github.io/argo-cd/user-guide/application_sources/[ArgoCD supported ways] to install Kubernetes resources are allowed.
| `path` | In case the Kubernetes resources are not in the root directory of the Git repo, set here the path.
| `revision` | Git revision/branch.
| `namespace` | Target namespace of the ArgoCD `Application` which will generated, not necessarily the target namespace of the capability itself.
| `project` | Referenced ArgoCD project.
| `ignores` | List of `ignoreDifferences` entries for the generated ArgoCD `Application`.
|===

The json object should be an *array*, the internal logic will iterate through the array and generate for any item an own ArgoCD `Application`.

== Summary

The cluster configuration represents the state of the cluster.

== References

N/A

== Open

N/A


== License

This article is licensed under the Apache License, Version 2.
Separate third-party code objects invoked within this code pattern are licensed by their respective providers pursuant
to their own separate licenses. Contributions are subject to the
link:https://developercertificate.org/[Developer Certificate of Origin, Version 1.1] and the
link:https://www.apache.org/licenses/LICENSE-2.0.txt[Apache License, Version 2].

See also link:https://www.apache.org/foundation/license-faq.html#WhatDoesItMEAN[Apache License FAQ]
.
