= OpenShift Recipes: Cluster Config
:author: Hafid Haddouti
:toc: macro
:toclevels: 4
:sectlinks:
:sectanchors:

Kubernetes/OpenShift GitOps - Manage the capabilities or your cluster. The cluster configuration.

toc::[]

== Overview

This section contains the Cluster Configuration part to configure ArgoCD with the desired cluster capabilities.
The installation and configuration is solved with `helm` and the link:helm/values.yaml[] contains the configuration for the desired capabilities.

== Installation

Generally this is not installed manually. During the link:../01-init[initialization] will be a new ArgoCD App configured and linked to this repo.


== Summary

The cluster configuration represents the state of the cluster.

== References

N/A

== Open

N/A


== License

This article is licensed under the Apache License, Version 2.
Separate third-party code objects invoked within this code pattern are licensed by their respective providers pursuant
to their own separate licenses. Contributions are subject to the
link:https://developercertificate.org/[Developer Certificate of Origin, Version 1.1] and the
link:https://www.apache.org/licenses/LICENSE-2.0.txt[Apache License, Version 2].

See also link:https://www.apache.org/foundation/license-faq.html#WhatDoesItMEAN[Apache License FAQ]
.
