= OpenShift Recipes: Init
:author: Hafid Haddouti
:toc: macro
:toclevels: 4
:sectlinks:
:sectanchors:

Kubernetes/OpenShift GitOps - Manage the capabilities or your cluster. The Initialization.

toc::[]

== Overview

This section contains the initialization part. It installs OpenShift GitOps with Argo CD and Tekton.

The first version of this solution used the ArgoCD link:https://argoproj.github.io/argo-cd/operator-manual/cluster-bootstrapping/[App of Apps pattern] to bootstrap and manage the dynamic list of applications.

The latest version use the new feature base on link:https://argocd-applicationset.readthedocs.io/en/stable/[ArgoCD ApplicationSet]. `ApplicationSet` generates `Application` resources using configuration from a static list or git repository.


== Installation

Install as follow - execute the script twice with a short wait period between both executions.
This is currently the simplest solution to install the base operator (here: OpenShift GitOps), wait that the operator is done before apply the ArgoCD configuration.
An alternative could be Ansible or similar - but this would increase the technology entry barrier.

----
$ git clone https://github.com/ocp-universe/ocp-recipes
$ oc apply -k 01-init/kustomize
namespace/openshift-gitops created
subscription.operators.coreos.com/openshift-gitops-operator created
unable to recognize "01-init/kustomize": no matches for kind "AppProject" in version "argoproj.io/v1alpha1"
unable to recognize "01-init/kustomize": no matches for kind "ApplicationSet" in version "argoproj.io/v1alpha1"


$ oc apply -k 01-init/kustomize
namespace/openshift-gitops unchanged
appproject.argoproj.io/argocd-bootstrap-project created
applicationset.argoproj.io/argocd-bootstrap-set created
subscription.operators.coreos.com/openshift-gitops-operator unchanged
----

Wait for that ArgoCD to be installed. The installation process also deploys an ArgoCD Application which links the link:../02-cluster-config[Cluster Config]. 

== Enhancements

=== ArgoCD with Vault Plugin


----
oc new-app --name argo-vault https://github.com/ocp-universe/ocp-recipes --context-dir=01-init/argocd-vault --strategy=Docker 
----

[source,yaml]
----
        initContainers:
        - resources: {}
          terminationMessagePath: /dev/termination-log
          name: download-tools
          command:
            - sh
            - '-c'
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: custom-tools
              mountPath: /custom-tools
          terminationMessagePolicy: File
          image: 'alpine:3.8'
          args:
            - >-
              echo "downloading..." && 
              wget -O /custom-tools/argocd-vault-plugin https://github.com/IBM/argocd-vault-plugin/releases/download/v1.0.0/argocd-vault-plugin_1.0.0_linux_amd64 &&

              chmod +x /custom-tools/argocd-vault-plugin 
        schedulerName: default-scheduler
        terminationGracePeriodSeconds: 30
        securityContext: {}
        containers:
            - resources: {}
            readinessProbe:
                tcpSocket:
                port: 8081
                initialDelaySeconds: 5
                timeoutSeconds: 1
                periodSeconds: 10
                successThreshold: 1
                failureThreshold: 3
            terminationMessagePath: /dev/termination-log
            name: argocd-repo-server
            command:
                - uid_entrypoint.sh
                - argocd-repo-server
                - '--redis'
                - 'argocd3-redis.openshift-gitops.svc.cluster.local:6379'
            livenessProbe:
                tcpSocket:
                port: 8081
                initialDelaySeconds: 5
                timeoutSeconds: 1
                periodSeconds: 10
                successThreshold: 1
                failureThreshold: 3
            ports:
                - name: server
                containerPort: 8081
                protocol: TCP
                - name: metrics
                containerPort: 8084
                protocol: TCP
            imagePullPolicy: Always
            volumeMounts:
                - name: ssh-known-hosts
                mountPath: /app/config/ssh
                - name: tls-certs
                mountPath: /app/config/tls
                - name: gpg-keyring
                mountPath: /app/config/gpg/keys
                - name: custom-tools
                mountPath: /usr/local/bin/argocd-vault-plugin
                subPath: argocd-vault-plugin
            terminationMessagePolicy: File
            image: >-
                registry.redhat.io/openshift-gitops-1/argocd-rhel8@sha256:1da88dd045197f3a64c9508e290fd64f23dc0648bc304f6416e952d9404bee57
        automountServiceAccountToken: false
        volumes:
            - name: ssh-known-hosts
            configMap:
                name: argocd-ssh-known-hosts-cm
                defaultMode: 420
            - name: tls-certs
            configMap:
                name: argocd-tls-certs-cm
                defaultMode: 420
            - name: gpg-keyring
            emptyDir: {}
            - name: custom-tools
            emptyDir: {}
        dnsPolicy: ClusterFirst
----



== Summary

This is the foundation for the GitOps solution to manage a Kubernetes/OpenShift cluster using Argo CD.

== References

* link:https://argoproj.github.io/argo-cd/operator-manual/cluster-bootstrapping/[App of Apps pattern]
* link:https://argocd-applicationset.readthedocs.io/en/stable/[ArgoCD ApplicationSet]

== Open

N/A


== License

This article is licensed under the Apache License, Version 2.
Separate third-party code objects invoked within this code pattern are licensed by their respective providers pursuant
to their own separate licenses. Contributions are subject to the
link:https://developercertificate.org/[Developer Certificate of Origin, Version 1.1] and the
link:https://www.apache.org/licenses/LICENSE-2.0.txt[Apache License, Version 2].

See also link:https://www.apache.org/foundation/license-faq.html#WhatDoesItMEAN[Apache License FAQ]
.
