= OpenShift Recipes: Init
:author: Hafid Haddouti
:toc: macro
:toclevels: 4
:sectlinks:
:sectanchors:

Kubernetes/OpenShift GitOps - Manage the capabilities or your cluster. The Initialization.

toc::[]

== Overview

This section contains the initialization part. It installs OpenShift GitOps with Argo CD and Tekton.

The first version of this solution used the ArgoCD link:https://argoproj.github.io/argo-cd/operator-manual/cluster-bootstrapping/[App of Apps pattern] to bootstrap and manage the dynamic list of applications.

The latest version use the new feature base on link:https://argocd-applicationset.readthedocs.io/en/stable/[ArgoCD ApplicationSet]. `ApplicationSet` generates `Application` resources using configuration from a static list or git repository.


== Installation

Install as follow

----
$ git clone https://github.com/ocp-universe/ocp-recipes
$ oc apply -k 01-init/kustomize
appproject.argoproj.io/argocd-bootstrap-project created
application.argoproj.io/00-argocd-bootstrap-config created
subscription.operators.coreos.com/openshift-gitops-operator created
----

Wait for that ArgoCD to be installed. The installation process also deploys an ArgoCD Application which links the link:../02-cluster-config[Cluster Config]. 

== Summary

This is the foundation for the GitOps solution to manage a Kubernetes/OpenShift cluster using Argo CD.

== References

* link:https://argoproj.github.io/argo-cd/operator-manual/cluster-bootstrapping/[App of Apps pattern]
* link:https://argocd-applicationset.readthedocs.io/en/stable/[ArgoCD ApplicationSet]

== Open

N/A


== License

This article is licensed under the Apache License, Version 2.
Separate third-party code objects invoked within this code pattern are licensed by their respective providers pursuant
to their own separate licenses. Contributions are subject to the
link:https://developercertificate.org/[Developer Certificate of Origin, Version 1.1] and the
link:https://www.apache.org/licenses/LICENSE-2.0.txt[Apache License, Version 2].

See also link:https://www.apache.org/foundation/license-faq.html#WhatDoesItMEAN[Apache License FAQ]
.
