= OpenShift Recipes: Init
:author: Hafid Haddouti
:toc: macro
:toclevels: 4
:sectlinks:
:sectanchors:

Kubernetes/OpenShift GitOps - Manage the capabilities or your cluster. The Initialization.

toc::[]

== Overview

This section contains the initialization part.

== Installation

Install as follow

----
$ git clone https://github.com/ocp-universe/ocp-recipes
$ oc apply -k 01-init/kustomize
appproject.argoproj.io/argocd-bootstrap-project created
application.argoproj.io/00-argocd-bootstrap-config created
subscription.operators.coreos.com/openshift-gitops-operator created
----

Wait for that ArgoCD to be installed. The installation process also deploys an ArgoCD Application which links the link:../02-cluster-config[Cluster Config]. 

== Summary

This is the foundation for the GitOps solution to manage a Kubernetes/OpenShift cluster.

== References

N/A

== Open

N/A


== License

This article is licensed under the Apache License, Version 2.
Separate third-party code objects invoked within this code pattern are licensed by their respective providers pursuant
to their own separate licenses. Contributions are subject to the
link:https://developercertificate.org/[Developer Certificate of Origin, Version 1.1] and the
link:https://www.apache.org/licenses/LICENSE-2.0.txt[Apache License, Version 2].

See also link:https://www.apache.org/foundation/license-faq.html#WhatDoesItMEAN[Apache License FAQ]
.
