= OpenShift Recipes: Init
:author: Hafid Haddouti
:toc: macro
:toclevels: 4
:sectlinks:
:sectanchors:

Kubernetes/OpenShift GitOps - Manage the capabilities or your cluster. The Initialization.

toc::[]

== Overview

This section contains the initialization part. It installs OpenShift GitOps with Argo CD. Newer version does not contains Tekton/OpenShift Pipelines anymore. Separat installation is needed and covered with the here provided configuration.

The first version of this solution used the ArgoCD link:https://argoproj.github.io/argo-cd/operator-manual/cluster-bootstrapping/[App of Apps pattern] to bootstrap and manage the dynamic list of applications.

The latest version use the new feature base on link:https://argocd-applicationset.readthedocs.io/en/stable/[ArgoCD ApplicationSet]. `ApplicationSet` generates `Application` resources using configuration from a static list or git repository.

.OpenShift GitOps
* v1.1.2
** ArgoCD 2.0.0

.OpenShift Pipeline
* v1.4.1 
** Tekton Pipelines: v0.22.0
** Tekton Triggers: v0.12.1
** ClusterTasks based on Tekton Catalog 0.22

== Installation

Install as follow - execute the script twice with a short wait period between both executions.
This is currently the simplest solution to install the base operator (here: OpenShift GitOps), wait that the operator is done before apply the ArgoCD configuration.
An alternative could be Ansible or similar - but this would increase the technology entry barrier.

----
$ git clone https://github.com/ocp-universe/ocp-recipes
$ oc apply -k 01-init/kustomize
namespace/openshift-gitops created
subscription.operators.coreos.com/openshift-gitops-operator created
unable to recognize "01-init/kustomize": no matches for kind "AppProject" in version "argoproj.io/v1alpha1"
unable to recognize "01-init/kustomize": no matches for kind "ApplicationSet" in version "argoproj.io/v1alpha1"


$ oc apply -k 01-init/kustomize
namespace/openshift-gitops unchanged
appproject.argoproj.io/argocd-bootstrap-project created
applicationset.argoproj.io/argocd-bootstrap-set created
subscription.operators.coreos.com/openshift-gitops-operator created
subscription.operators.coreos.com/openshift-pipelines-operator-rh created
----

Wait for that ArgoCD to be installed. The installation process also deploys an ArgoCD Application which links the link:../02-cluster-config[Cluster Config]. 
Depends on the Cluster-Config you will have no or the first capabilities as ArgoCD Applications configured and initialized.

== Enhancements

=== ArgoCD with Vault Plugin

in preparation


== Summary

This is the foundation for the GitOps solution to manage a Kubernetes/OpenShift cluster using Argo CD.

== References

* link:https://argoproj.github.io/argo-cd/operator-manual/cluster-bootstrapping/[App of Apps pattern]
* link:https://argocd-applicationset.readthedocs.io/en/stable/[ArgoCD ApplicationSet]

== Open

N/A


== License

This article is licensed under the Apache License, Version 2.
Separate third-party code objects invoked within this code pattern are licensed by their respective providers pursuant
to their own separate licenses. Contributions are subject to the
link:https://developercertificate.org/[Developer Certificate of Origin, Version 1.1] and the
link:https://www.apache.org/licenses/LICENSE-2.0.txt[Apache License, Version 2].

See also link:https://www.apache.org/foundation/license-faq.html#WhatDoesItMEAN[Apache License FAQ]
.
