# Red Hat Kiali Operator
# 
# kiali-operator
# Version: 1.24.6, channel: stable
#
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  generation: 1  
  name: kiali-ossm
  namespace: openshift-operators
  labels:
    operators.coreos.com/elasticsearch-operator.openshift-operators-redhat: ""
spec:
  channel: stable
  installPlanApproval: Automatic
  name: kiali-ossm
  source: redhat-operators
  sourceNamespace: openshift-marketplace
  startingCSV: kiali-operator.v1.24.6
---

