# Operator instances
# 
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: argocd-role
  namespace: open-cluster-management
  annotations:
    argocd.argoproj.io/sync-wave: "2"
rules:
# Permissions to create resources in associated Tasks
- apiGroups: ["operator.open-cluster-management.io"]
  resources: ["multiclusterhubs"]
  verbs: ["create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: argocd-role-binding
  namespace: open-cluster-management
  annotations:
    argocd.argoproj.io/sync-wave: "2"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: argocd-role
subjects:
- kind: ServiceAccount
  name: openshift-gitops-argocd-application-controller
  namespace: openshift-gitops
---