# helm-jaeger.
# 

operator:
  name: jaeger-product
  namespace: openshift-operators
  channel: stable
  approval: Automatic
  source: redhat-operators
  sourceNamespace: openshift-marketplace
  version: jaeger-operator.v1.20.3


